#PyTorch Fundamentals


##Introduction to tensors

###Scalar

In [ ]:
import torch
torch.__version__

'2.0.1+cu118'

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

###Vectors

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

###Matrix

In [ ]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

###Tensor

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
#creatte a random tensor of size (3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype, random_tensor.ndim

(tensor([[0.8828, 0.2491, 0.3847, 0.7439],
         [0.1389, 0.3424, 0.7614, 0.1869],
         [0.3787, 0.2831, 0.6396, 0.8866]]),
 torch.float32,
 2)

In [ ]:
#create a random tensorof size (224,224,3)
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###Zeros and Ones

In [ ]:
#create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
zeros.ndim

2

In [ ]:
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

###Creating range of tensors

In [ ]:
#using torch.arange(), torch.range()
zero_to_ten_depricated = torch.range(0,10)

#create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

<ipython-input-18-66cca26d4cac>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_depricated = torch.range(0,10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# creating a tensor similar to the other tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Default datatype for tensor is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,
                               device = None,
                               requires_grad = False) # if true the operations performed on the tensors are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

###Getting information from tensors

In [ ]:
some_tensors = torch.rand(3,4)
print(some_tensors)
print(f"Shape of tensor: {some_tensors.shape}")
print(f"Datatype of tensor: {some_tensors.dtype}")
print(f"Device tensor is stored on: {some_tensors.device}")

tensor([[0.9780, 0.4474, 0.6005, 0.5240],
        [0.1613, 0.8133, 0.7629, 0.3035],
        [0.1835, 0.2015, 0.7316, 0.8551]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


###Basic operations

In [ ]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [ ]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [ ]:
print(tensor, "*", tensor)
print("Equals: ", tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:  tensor([1, 4, 9])


###Matrix Multiplication

In [ ]:
import torch
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [ ]:
#Elemnt wise matrix multiplication
tensor*tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
#same as the above
tensor@tensor

tensor(14)

In [ ]:
%%time
#Matrix multiplactaion by hand
#avioid using using matrix multpliactions using for loops as they are compultationally expensive

value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 316 µs, sys: 0 ns, total: 316 µs
Wall time: 334 µs


tensor(14)

In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 68 µs, sys: 13 µs, total: 81 µs
Wall time: 84.4 µs


tensor(14)

Transpose operation in PyTorch:

- **torch.transpose(input, dim0, dim1) -** where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.

- **tensor.T -** where tensor is the desired tensor to transpose

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]], dtype = torch.float32)

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]], dtype = torch.float32)

In [ ]:
print(tensor_A.T)
print(tensor_B.T)

tensor([[1., 3., 5.],
        [2., 4., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

**NOTE:** The neural networks are full of matrix multiplications

**The torch.nn.Linear()** also known as as a **feed forward layer or fully connected layer** implements a matrix multiplication between an input X and a weights matrix A.

y = x.A^T + b

where,

 - x is the input to the layer.
 - A is the weights matrix created by the layer(starts as random numbers but gets adjusted to fit and represent the patterns).
 - b is the bias term used to slightly offset the weights and inputs.
 - y is the output ( a manipulation of inputs in the hopes to discover patterns in it)

In [ ]:
#since the linear layer starts with a random weights lets make it reproducable
torch.manual_seed(42)

# This used matrix multiplication
linear = torch.nn.Linear(in_features =2, # in_features = matches inner dimension of input
                         out_features = 6) # out_features = describe outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


###Finding the min, max, mean, sum, etc(aggregation)

In [ ]:
# create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
#print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # wont work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [ ]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

###Positional min/max

In [ ]:
tensor = torch.arange(10,100,10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


###Change data types of tensors

In [ ]:
tensor = torch.arange(10.,100.,10.)
tensor.dtype

torch.float32

In [ ]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

###Reshaping, Stacking, Squeezing and Unsqueezing

**METHODS:**

1. **torch.reshape(input,shape)** - Reshapes input to shape(if compatible) can also use **torch.Tensor.reshape()**.

2. **Tensor.view(shape)** - Returns a view of the original tensor in a different shape but shares the same data as the original tensor.

3. **torch.stack(tensors, dim=0)** - Concatinates a sequence of tensors along a new dimension(dim), all the tensors must be same size.

4. **torch.squeeze(input)** - Squeezes input to remove all the dimensions with value 1.

5. **torch.unsqueeze(input, dim)** - Returns input with a dimesion value of 1 added at dim.

6. **torch.permute(input, dims)** - Returns a view of the original input with its dimesnions permuted(rearranged) to dims.

In [ ]:
x = torch.arange(1.,8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
#changing z changes x
z[:,0]=5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New Shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New Shape: torch.Size([7])


In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Add an extra dimesnion with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"New Shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New Shape: torch.Size([1, 7])


In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224,224,3))

# Permute the original tensor to rearragnge the axis order
x_permuted = x_original.permute(2,0,1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


###Indexing (selecting data from tensors)

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
print(f"First square bracket:\n {x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [ ]:
# Get all the values of the 1th dimensions
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
#Get all the values of the 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all the values of the 0 dimensions but only the 1 index values of the 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
# Get index 0 of the 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

###PyTorch Tensors and NumPy

 - **torch.from_numpy(ndarray)** - NumPy array -> PyTorch tensor.

 - **torch.Tensor.numpy()** - PyTorch tensor -> NumPy array.

In [ ]:
# NumPy array to tensor
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# by default the numpy type is float64, for to convert it into float32
tensor = torch.from_numpy(array).type(torch.float32)
tensor.dtype

torch.float32

In [ ]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7) #create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() #will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

###Reproducibility

In [ ]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.4563, 0.9719, 0.3968, 0.1496],
        [0.4743, 0.9973, 0.4436, 0.9726],
        [0.5194, 0.5337, 0.7050, 0.3362]])

Tensor B:
tensor([[0.7891, 0.1694, 0.1800, 0.7177],
        [0.6988, 0.5510, 0.2485, 0.8518],
        [0.0963, 0.1338, 0.2741, 0.6142]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
import random

RANDOM_SEED = 42

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])